config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'location#index'

  get 'admin/report' => 'location#report', as: :user_location_report
  post 'admin/report' => 'location#report_post', as: :user_location_report_post
  post '' => 'location#record'
  post 'admin/message/last_message' => 'message#last_message'
  post 'admin/message/file' => 'message#save_file'
  post 'register' => 'car#register'
  post 'login' => 'car#login'
  get 'admin' => 'admin#index'
  get 'admin/create' => 'admin#create'
  post 'admin/login' => 'admin#login'
  get 'admin/user' => 'car#car'
  get 'admin/user/:id/edit' => 'car#edit', as: :admin_car_edit
  post 'admin/user/:id/update' => 'car#update', as: :admin_car_update
  get 'admin/user/new' => 'car#new', as: :admin_car_new
  post 'admin/user/create' => 'car#create', as: :admin_car_create
  delete 'admin/user/:id/delete' => 'car#delete', as: :admin_car_delete
  get 'admin/map' => 'map#index', as: :admin_google_map
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :locations, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :car
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :car

  attr_accessor :upload

  def self.save_file(upload, file_name)

    file = upload.read
    image_root = "public/messages_images"

    unless File.directory?(image_root)
      Dir.mkdir(image_root)
    end

    File.open(image_root + "/" + file_name, "wb")  do |f|
      f.write(file)
    end

  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @admins = Admin::all
    render :json => @admins
  end
  def create
    username = (0...8).map { (65 + rand(16)).chr }.join
    @admins = Admin.create(:username => username, :password => username, :lat => 0.0, :lng => 0.0)
    if @admins.save
      render :json => @admins
    else
      render :json => { error: "Couldn't create car", status: 500 }
    end
  end
  def login
    @admin = Admin.select(:id, :username, :password, :lat, :lng).find_by(admin_login_params)
    if @admin.present?
      render :json => @admin
    else
      render :json => { error: "Couldn't find any admin", status: 500 }, status: 400
    end
  end

  private
    def admin_login_params
      params.require(:admin).permit(:username, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/car_controller.rb
class CarController < ApplicationController
  protect_from_forgery with: :null_session

  def register
    @car = Car.new(car_params)
    if @car.save
      render :json => Car.all
    else
      render :json =>  { error: "Couldn't create car", status: 500 }
    end
  end

  def login
    @car = Car.select(:id, :number, :username, :latitude, :longitude).find_by(car_params)
    if @car.present?
      render :json => @car, status: 200
    else
      render :json =>  { error: "Couldn't find any car", status: 500 }, status: 400
    end
  end

  def car
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to admin_user_path
    else
      render admin_car_new_path
    end
  end

  def delete
    @car = Car.find(params[:id])
    if @car.destroy
      redirect_to admin_user_path
    else
      render admin_user_path
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to admin_user_path
  end

  private
    def car_params
      params.require(:car).permit(:number, :username)
    end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token

  def index
    @cars = Car.all
    render :json => @cars
  end

  def record
    Car.update(params[:location][:id], :longitude => params[:location][:longitude], :latitude => params[:location][:latitude])
    @cars = Car.all
    @location = Location.new(location_params)
    if @location.save
      render :json => { :cars => @cars }
    else
      render :json =>  { error: "Couldn't create locations", status: 500 }
    end
  end

  def report
    @cars = Car.all
  end

  def report_post
    @cars = Car.all
    @driver = Car.find(report_params[:car_id])
    @start = report_params[:picker_start]
    @finish = report_params[:picker_finish]
    @locations = Location.select("latitude as lat, longitude as lng").where("car_id = ? AND created_at >= ? AND created_at <= ?", report_params[:car_id], report_params[:picker_start], report_params[:picker_finish])
  end

  private
    def location_params
      params.require(:location).permit(:username, :longitude, :latitude, :car_id)
    end

    def report_params
      params.permit(:car_id, :picker_start, :picker_finish)
    end

    def car_params
      params.require(:location).permit(:id, :longitude, :latitude)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController

  def index
    @cars = Car.all
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token

  def index
    @messages = Message.all
  end

  def last_message
    @user = Car.find(last_message_params[:car_id])
    @messages = Message.select(:id, :car_id, :file, :created_at, :length).where('messages.created_at > :last_user_message and messages.car_id != :car_id', :last_user_message => @user.last_message_date, :car_id => @user.id)
    if @messages.length > 0
      @user.last_message_date = @messages.last.created_at
      if @user.save
        render :json => @messages
      else
        render :json => {:status => 500, :message => 'Can\'t update'}
      end
    else
      render :json => {}
    end
  end

  def create_file_message

  end

  def save_file
    @driver = Car.select(:id, :username).where(id: message_params[:car_id]).first
    time_now = Time.now.strftime("%d_%m_%Y_%H_%M_%S")
    file_name = @driver.username + "_#{time_now}"
    file = message_params[:file]
    original_file_name = file.original_filename  if  (file !='')
    file_type = original_file_name.split('.').last
    file_name = "#{file_name}." + file_type

    if ['mp3', 'mp4'].include?(file_type)
      Message.save_file(message_params[:file], file_name)
      @message = Message.new(:file => file_name, :car_id => message_params[:car_id], :length => message_params[:length])
      if @message.save
        render :json => @message
      end
    else
      render :json => {:status => 'Error', :code => 500 }
    end
  end

  private

  def message_params
    params.permit(:file, :car_id, :length)
  end

  def last_message_params
    params.permit(:car_id, :datetime)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/views/car/car.html.erb
<% content_for :body do %>
  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Имя</th>
        <th>Номер</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td><%= car.id %></td>
          <td><%= link_to car.username, admin_car_edit_path(car.id) %></td>
          <td><%= car.number %></td>
          <td><p><%= link_to 'Удалить', admin_car_delete_path(car.id),
                             method: :delete,
                             data: { confirm: 'Are you sure?' } %></p>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/car/edit.html.erb
<% content_for :body do %>

  <h1>Обновить водитель</h1>

  <%= form_for @car, :html => {:class => 'form'}, :url => admin_car_update_path(id: @car.id), :method => :POST do |c| %>
    <div class="form-group">
      <%= c.label "Имя" %><br>
      <%= c.text_field :username, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= c.label "Номер" %><br>
      <%= c.text_field :number, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= c.submit "Обновить", class: 'btn btn-default' %>
    </div>
  <% end %>

<% end %>

app/views/car/new.html.erb
<% content_for :body do %>
  <h1>Новый водитель</h1>

  <%= form_for @car, :url => admin_car_create_path, :method => :POST do |c| %>
    <div class="form-group">
      <%= c.label 'Водитель' %><br>
      <%= c.text_field :username, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= c.label 'Номер' %><br>
      <%= c.text_field :number, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= link_to 'Отменить', admin_user_path, class: 'btn btn-danger btn-link' %>
      <%= c.submit 'Создать', class: 'btn btn-default' %>
    </div>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Howo</title>
    <%= csrf_meta_tags %>

    <meta name="turbolinks-cache-control" content="no-cache">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= yield :head %>
  </head>

  <body>

  <div class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Водители', admin_user_path %></li>
            <li><%= link_to 'Создать новый водитель', admin_car_new_path %></li>
            <li><%= link_to 'Карта', admin_google_map_path %></li>
            <li><%= link_to 'Отчет', user_location_report_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>



    <div class="row">
      <div class="col-sm-12">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield(:body) %>
      </div>
    </div>
  </div>
  </body>
  <%= yield :footer %>
</html>

app/views/location/report.html.erb
<% content_for :body do %>

  <%= form_tag user_location_report_post_path do %>
    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <select class="form-control" id="car_id" name="car_id">
            <% @cars.each do |car| %>
              <option value="<%= car.id %>"><%= [car.number, car.username].join("-") %></option>
            <% end %>
          </select>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <div class="input-group date">
            <input type='text' class="form-control" name="picker_start" id="picker_start"/>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class='col-sm-3'>
        <div class="form-group">
          <div class="input-group date">
            <input type='text' class="form-control" name="picker_finish" id="picker_finish"/>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class='col-sm-3'>
        <div class="form-group">
          <div class='input-group'>
            <input type='submit' class="btn btn-primary" value="Отправить"/>
          </div>
        </div>
      </div>
    </div>
  <% end %>

<% end %>

<% content_for :footer do %>
  <%= javascript_include_tag 'application', 'bootstrap-datepicker/bootstrap-datepicker' %>
  <%= javascript_include_tag 'application', 'bootstrap-datepicker/locales/bootstrap-datepicker.ru.min' %>
<% end %>

app/views/location/report_post.html.erb
<% content_for :body do %>

  <%= form_tag user_location_report_post_path do %>
    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <select class="form-control" id="car_id" name="car_id">
            <% @cars.each do |car| %>
              <option value="<%= car.id %>"><%= [car.number, car.username].join("-") %></option>
            <% end %>
          </select>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <div class="input-group date">
            <input type='text' class="form-control" name="picker_start" id="picker_start"/>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class='col-sm-3'>
        <div class="form-group">
          <div class="input-group date">
            <input type='text' class="form-control" name="picker_finish" id="picker_finish"/>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class='col-sm-3'>
        <div class="form-group">
          <div class='input-group'>
            <input type='submit' class="btn btn-primary" value="Отправить"/>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <hr>
  <p>Водитель: <%= @driver.username %></p>
  <p>Дата начало: <%= @start %></p>
  <p>Дата финиш: <%= @finish %></p>
  <p id="meter">Метер:</p>
  <hr>

  <div id="map" style="width:100%;height:500px;"></div>
<% end %>

<% content_for :footer do %>
  <script type="application/javascript">
      function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
          var R = 6371000;
          var dLat = deg2rad(lat2-lat1);
          var dLon = deg2rad(lon2-lon1);
          var a =
              Math.sin(dLat/2) * Math.sin(dLat/2) +
              Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) *
              Math.sin(dLon/2) * Math.sin(dLon/2)
          ;
          var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
          return R * c;
      }

      function deg2rad(deg) {
          return deg * (Math.PI/180)
      }
      function initMap() {
          var carsCoordinates = [];
          var lat;
          var lng;
          var countSum = 0;
          var bounds = new google.maps.LatLngBounds();


          <% @locations.each do |location| %>
            carsCoordinates.push({lat: <%= location.lat %>,lng: <%= location.lng %>});
            if (typeof lat !== 'undefined')
            {
                countSum += getDistanceFromLatLonInKm(lat, lng, <%= location.lat %>, <%= location.lng %>);
            }
            lat = <%= location.lat %>;
            lng = <%= location.lng %>;

          <% end %>
          $("#meter").text("Метер: " + countSum.toFixed(2) + "м.");
          console.log(countSum);
          var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 14,
              center: {lat: 42.843718, lng: 74.576779},
              mapTypeId: 'terrain'
          });
          var infowindow = new google.maps.InfoWindow();

          var flightPath = new google.maps.Polyline({
              path: carsCoordinates,
              geodesic: true,
              strokeColor: '#FF0000',
              strokeOpacity: 1.0,
              strokeWeight: 2
          });

          var startMarker = new google.maps.Marker({
              position: flightPath.getPath().getAt(0),
              map:map,
              icon: "/icons/plowtruck.png"
          });
          var endMarker =  new google.maps.Marker({
              position: flightPath.getPath().getAt(flightPath.getPath().getLength()-1),
              map:map,
              icon: "/icons/plowtruck.png"
          });

          google.maps.event.addListener(startMarker, 'click', (function(startMarker) {
              return function() {
                  infowindow.setContent("<h1>" + 'Старт' + "</h1>");
                  infowindow.open(map, startMarker);
              }
          })(startMarker));

          google.maps.event.addListener(endMarker, 'click', (function(endMarker) {
              return function() {
                  infowindow.setContent("<h1>" + 'Финиш' + "</h1>");
                  infowindow.open(map, endMarker);
              }
          })(endMarker));

          startMarker.setMap(map);
          endMarker.setMap(map);

          flightPath.setMap(map);
          if(carsCoordinates.length > 2)
          {
              bounds.extend(startMarker.position);
              bounds.extend(endMarker.position);
              map.fitBounds(bounds);
          }
      }
  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCOgqhNZ6wm4erDsuykUx48_WSJq38urgM&callback=initMap"></script>
<% end %>

app/views/map/index.html.erb
<% content_for :body do %>

  <div id="googleMap" style="width:100%;height:500px;"></div>
<% end %>

<% content_for :footer do %>
  <script type="text/javascript" src="http://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
  <script type="application/javascript">
    if(window.google){
        myMap();
    }
    else{
        $.ajax('https://maps.googleapis.com/maps/api/js?key=AIzaSyCOgqhNZ6wm4erDsuykUx48_WSJq38urgM&callback=myMap', {
            crossDomain: true,
            dataType: 'script'
        });
    }
    function myMap() {

        var myLatLng = {lat: 42.876048, lng: 74.656599};
        var bounds = new google.maps.LatLngBounds();


        var mapProp = {
            center: myLatLng,
            zoom: 11
        };
        var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        var markers = [];

        <% @cars.each do |car| %>
        var myLatLong = {lat: <%= car.latitude %> , lng: <%= car.longitude %>};

        var infowindow = new google.maps.InfoWindow();
        var myMarker = new google.maps.Marker({
            position: myLatLong,
            map: map,
            draggable:true,
            icon: "/icons/plowtruck.png",
            animation: google.maps.Animation.DROP,
            title: "<%= car.username %>"
        });
        bounds.extend(myMarker.position);
        myMarker.setMap(map);
        google.maps.event.addListener(myMarker, 'click', (function(myMarker) {
            return function() {
                infowindow.setContent("<h1>" + '<%= car.username %>' + "</h1>");
                infowindow.open(map, myMarker);
            }
        })(myMarker));
        markers.push(myMarker);
        <% end %>
        setInterval(function () {

            $.ajax({
                url: '<%= Rails.application.routes.url_helpers.root_path %>',
                method: 'get',
                success: function (data) {
                    var bounds = new google.maps.LatLngBounds();
                    $.each(data, function (key, value) {
                        var myLatLong = { lat: parseFloat(value.latitude), lng: parseFloat(value.longitude) };
                        if(typeof markers[key] === 'undefined') {

                            var myMarker = new google.maps.Marker({
                                position: myLatLong,
                                map: map,
                                draggable:true,
                                icon: "/icons/plowtruck.png",
                                animation: google.maps.Animation.DROP,
                                title: value.username
                            });
                            bounds.extend(myMarker.position);
                            myMarker.setMap(map);
                            google.maps.event.addListener(myMarker, 'click', (function(myMarker) {
                                return function() {
                                    infowindow.setContent("<h1>" + value.username + "</h1>");
                                    infowindow.open(map, myMarker);
                                }
                            })(myMarker));
                            markers.push(myMarker);
                        }
                        else{
                            markers[key].setPosition(myLatLong);
                            bounds.extend(markers[key].position);
                            map.fitBounds(bounds);
                        }
                    });
                },
                error: function () {
                    console.log('error ajax');
                }
            });

        }, 2000);

        map.fitBounds(bounds);
        function setMapOnAll(map) {
            for (var i = 0; i < markers.length; i++) {
                markers[i].setMap(map);
            }
        }
    }
    function toggleBounce() {
        if (marker.getAnimation() !== null) {
            marker.setAnimation(null);
        } else {
            marker.setAnimation(google.maps.Animation.BOUNCE);
        }
    }
  </script>
<% end %>